name: Build, Test and Publish NuGet Package

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]  # Only publish on version tags like v1.2.3
  workflow_dispatch:     # Allow manual trigger

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build
        run: dotnet build ./src/KPasswordGenerator.sln --configuration Release

      - name: Run tests
        run: dotnet test ./src/KPasswordGenerator.sln

      - name: Pack NuGet package
        run: dotnet pack ./src/KPasswordGenerator.sln --configuration Release -o package

      #- name: Push to NuGet
      #  if: startsWith(github.ref, 'refs/tags/v')
      #  run: dotnet nuget push "./nupkg/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
